################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/ak09918_driver.c \
../Core/Src/ak09918_reg.c \
../Core/Src/ak09918_selftest.c \
../Core/Src/bf2092_driver.c \
../Core/Src/bu27030_driver.c \
../Core/Src/calibration_data.c \
../Core/Src/chbsp_chirp_dvb.c \
../Core/Src/flash_interface.c \
../Core/Src/freertos.c \
../Core/Src/led_aw21036_driver.c \
../Core/Src/led_aw9110_driver.c \
../Core/Src/lsm6dso_config.c \
../Core/Src/lsm6dso_driver.c \
../Core/Src/lsm6dso_reg.c \
../Core/Src/main.c \
../Core/Src/rotation_vector.c \
../Core/Src/sensor_device.c \
../Core/Src/speed_vector.c \
../Core/Src/stm32f4xx_hal_msp.c \
../Core/Src/stm32f4xx_hal_timebase_tim.c \
../Core/Src/stm32f4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32f4xx.c \
../Core/Src/tof_vl53l5.c 

OBJS += \
./Core/Src/ak09918_driver.o \
./Core/Src/ak09918_reg.o \
./Core/Src/ak09918_selftest.o \
./Core/Src/bf2092_driver.o \
./Core/Src/bu27030_driver.o \
./Core/Src/calibration_data.o \
./Core/Src/chbsp_chirp_dvb.o \
./Core/Src/flash_interface.o \
./Core/Src/freertos.o \
./Core/Src/led_aw21036_driver.o \
./Core/Src/led_aw9110_driver.o \
./Core/Src/lsm6dso_config.o \
./Core/Src/lsm6dso_driver.o \
./Core/Src/lsm6dso_reg.o \
./Core/Src/main.o \
./Core/Src/rotation_vector.o \
./Core/Src/sensor_device.o \
./Core/Src/speed_vector.o \
./Core/Src/stm32f4xx_hal_msp.o \
./Core/Src/stm32f4xx_hal_timebase_tim.o \
./Core/Src/stm32f4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32f4xx.o \
./Core/Src/tof_vl53l5.o 

C_DEPS += \
./Core/Src/ak09918_driver.d \
./Core/Src/ak09918_reg.d \
./Core/Src/ak09918_selftest.d \
./Core/Src/bf2092_driver.d \
./Core/Src/bu27030_driver.d \
./Core/Src/calibration_data.d \
./Core/Src/chbsp_chirp_dvb.d \
./Core/Src/flash_interface.d \
./Core/Src/freertos.d \
./Core/Src/led_aw21036_driver.d \
./Core/Src/led_aw9110_driver.d \
./Core/Src/lsm6dso_config.d \
./Core/Src/lsm6dso_driver.d \
./Core/Src/lsm6dso_reg.d \
./Core/Src/main.d \
./Core/Src/rotation_vector.d \
./Core/Src/sensor_device.d \
./Core/Src/speed_vector.d \
./Core/Src/stm32f4xx_hal_msp.d \
./Core/Src/stm32f4xx_hal_timebase_tim.d \
./Core/Src/stm32f4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32f4xx.d \
./Core/Src/tof_vl53l5.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/ak09918_driver.o: ../Core/Src/ak09918_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/ak09918_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/ak09918_reg.o: ../Core/Src/ak09918_reg.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/ak09918_reg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/ak09918_selftest.o: ../Core/Src/ak09918_selftest.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/ak09918_selftest.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/bf2092_driver.o: ../Core/Src/bf2092_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/bf2092_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/bu27030_driver.o: ../Core/Src/bu27030_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/bu27030_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/calibration_data.o: ../Core/Src/calibration_data.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/calibration_data.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/chbsp_chirp_dvb.o: ../Core/Src/chbsp_chirp_dvb.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/chbsp_chirp_dvb.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/flash_interface.o: ../Core/Src/flash_interface.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/flash_interface.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/freertos.o: ../Core/Src/freertos.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/freertos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/led_aw21036_driver.o: ../Core/Src/led_aw21036_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/led_aw21036_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/led_aw9110_driver.o: ../Core/Src/led_aw9110_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/led_aw9110_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/lsm6dso_config.o: ../Core/Src/lsm6dso_config.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/lsm6dso_config.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/lsm6dso_driver.o: ../Core/Src/lsm6dso_driver.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/lsm6dso_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/lsm6dso_reg.o: ../Core/Src/lsm6dso_reg.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/lsm6dso_reg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/rotation_vector.o: ../Core/Src/rotation_vector.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/rotation_vector.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sensor_device.o: ../Core/Src/sensor_device.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sensor_device.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/speed_vector.o: ../Core/Src/speed_vector.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/speed_vector.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_hal_msp.o: ../Core/Src/stm32f4xx_hal_msp.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_hal_timebase_tim.o: ../Core/Src/stm32f4xx_hal_timebase_tim.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_hal_timebase_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_it.o: ../Core/Src/stm32f4xx_it.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32f4xx.o: ../Core/Src/system_stm32f4xx.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/tof_vl53l5.o: ../Core/Src/tof_vl53l5.c Core/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/chirp/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x08040000/bare_driver/platform/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/tof_vl53l5.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

