################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../chirp/src/ch101_gpr_open.c \
../chirp/src/ch101_gpr_open_fw.c \
../chirp/src/ch101_gpr_sr_open.c \
../chirp/src/ch101_gpr_sr_open_fw.c \
../chirp/src/ch201_gprmt.c \
../chirp/src/ch201_gprmt_fw.c \
../chirp/src/ch_api.c \
../chirp/src/ch_common.c \
../chirp/src/ch_driver.c \
../chirp/src/chbsp_dummy.c 

OBJS += \
./chirp/src/ch101_gpr_open.o \
./chirp/src/ch101_gpr_open_fw.o \
./chirp/src/ch101_gpr_sr_open.o \
./chirp/src/ch101_gpr_sr_open_fw.o \
./chirp/src/ch201_gprmt.o \
./chirp/src/ch201_gprmt_fw.o \
./chirp/src/ch_api.o \
./chirp/src/ch_common.o \
./chirp/src/ch_driver.o \
./chirp/src/chbsp_dummy.o 

C_DEPS += \
./chirp/src/ch101_gpr_open.d \
./chirp/src/ch101_gpr_open_fw.d \
./chirp/src/ch101_gpr_sr_open.d \
./chirp/src/ch101_gpr_sr_open_fw.d \
./chirp/src/ch201_gprmt.d \
./chirp/src/ch201_gprmt_fw.d \
./chirp/src/ch_api.d \
./chirp/src/ch_common.d \
./chirp/src/ch_driver.d \
./chirp/src/chbsp_dummy.d 


# Each subdirectory must supply rules for building sources it contributes
chirp/src/ch101_gpr_open.o: ../chirp/src/ch101_gpr_open.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch101_gpr_open.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch101_gpr_open_fw.o: ../chirp/src/ch101_gpr_open_fw.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch101_gpr_open_fw.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch101_gpr_sr_open.o: ../chirp/src/ch101_gpr_sr_open.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch101_gpr_sr_open.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch101_gpr_sr_open_fw.o: ../chirp/src/ch101_gpr_sr_open_fw.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch101_gpr_sr_open_fw.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch201_gprmt.o: ../chirp/src/ch201_gprmt.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch201_gprmt.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch201_gprmt_fw.o: ../chirp/src/ch201_gprmt_fw.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch201_gprmt_fw.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch_api.o: ../chirp/src/ch_api.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch_common.o: ../chirp/src/ch_common.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/ch_driver.o: ../chirp/src/ch_driver.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/ch_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
chirp/src/chbsp_dummy.o: ../chirp/src/chbsp_dummy.c chirp/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F405xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/config" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/api/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/common/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/core/dci/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/bare_driver/platform/inc" -I"/home/PDF/12leds/athena_sensor_src/k91_main_source.0x080A0000/chirp/inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"chirp/src/chbsp_dummy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

